<h2>Importing the libraries </h2>

In [1]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,Flatten,Dense
from tensorflow.keras.models import Sequential
import cv2 as cv

In [2]:
!unzip "/content/drive/MyDrive/Bird_species.zip"

Archive:  /content/drive/MyDrive/Bird_species.zip
  inflating: test_data/test_data/blasti/DSC_6396.jpg  
  inflating: test_data/test_data/blasti/DSC_6397.jpg  
  inflating: test_data/test_data/blasti/DSC_6398.jpg  
  inflating: test_data/test_data/blasti/DSC_6399.jpg  
  inflating: test_data/test_data/blasti/DSC_6400.jpg  
  inflating: test_data/test_data/blasti/DSC_6401.jpg  
  inflating: test_data/test_data/blasti/DSC_6402.jpg  
  inflating: test_data/test_data/blasti/DSC_6403.jpg  
  inflating: test_data/test_data/blasti/DSC_6405.jpg  
  inflating: test_data/test_data/blasti/DSC_6406.jpg  
  inflating: test_data/test_data/blasti/DSC_6407.jpg  
  inflating: test_data/test_data/blasti/DSC_6408.jpg  
  inflating: test_data/test_data/blasti/DSC_6409.jpg  
  inflating: test_data/test_data/blasti/DSC_6410.jpg  
  inflating: test_data/test_data/blasti/DSC_6411.jpg  
  inflating: test_data/test_data/bonegl/DSC_4587.jpg  
  inflating: test_data/test_data/bonegl/DSC_4588.jpg  
  inflating: te

In [3]:
train_gen = ImageDataGenerator(rescale = (1./255),horizontal_flip=True,shear_range=0.2,zoom_range=0.2)
test_gen = ImageDataGenerator(rescale = (1./255))

In [4]:
train=train_gen.flow_from_directory('/content/train_data/train_data',
                                    target_size=(120,120),
                                    class_mode='categorical',
                                    batch_size=8)
test=test_gen.flow_from_directory('/content/test_data/test_data',
                                  target_size=(120,120),
                                    class_mode='categorical',
                                    batch_size=8)

Found 150 images belonging to 16 classes.
Found 157 images belonging to 16 classes.


In [5]:
model = Sequential([
    Convolution2D(20,(3,3),activation = 'relu',input_shape=(120,120,3)),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(45,activation = 'relu'),
    Dense(16,activation = 'softmax')
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 118, 118, 20)      560       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 59, 59, 20)       0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 69620)             0         
                                                                 
 dense (Dense)               (None, 45)                3132945   
                                                                 
 dense_1 (Dense)             (None, 16)                736       
                                                                 
Total params: 3,134,241
Trainable params: 3,134,241
Non-trainable params: 0
______________________________________________

In [6]:
train.class_indices

{'blasti': 0,
 'bonegl': 1,
 'brhkyt': 2,
 'cbrtsh': 3,
 'cmnmyn': 4,
 'gretit': 5,
 'hilpig': 6,
 'himbul': 7,
 'himgri': 8,
 'hsparo': 9,
 'indvul': 10,
 'jglowl': 11,
 'lbicrw': 12,
 'mgprob': 13,
 'rebimg': 14,
 'wcrsrt': 15}

In [7]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='categorical_crossentropy')

In [8]:
model_fit = model.fit(train,epochs =20,
                     validation_data = test ,batch_size=5)

Epoch 1/20
19/19 [==============================] - 132s 7s/step - loss: 3.8991 - accuracy: 0.1000 - val_loss: 2.7298 - val_accuracy: 0.1338
Epoch 2/20
19/19 [==============================] - 119s 7s/step - loss: 2.6869 - accuracy: 0.1800 - val_loss: 2.7484 - val_accuracy: 0.1401
Epoch 3/20
19/19 [==============================] - 87s 5s/step - loss: 2.6594 - accuracy: 0.1533 - val_loss: 2.8133 - val_accuracy: 0.0892
Epoch 4/20
19/19 [==============================] - 87s 5s/step - loss: 2.6375 - accuracy: 0.1600 - val_loss: 2.8060 - val_accuracy: 0.1529
Epoch 5/20
19/19 [==============================] - 85s 5s/step - loss: 2.5822 - accuracy: 0.1133 - val_loss: 2.8158 - val_accuracy: 0.1401
Epoch 6/20
19/19 [==============================] - 88s 5s/step - loss: 2.5227 - accuracy: 0.1200 - val_loss: 2.8088 - val_accuracy: 0.1083
Epoch 7/20
19/19 [==============================] - 86s 5s/step - loss: 2.3833 - accuracy: 0.1733 - val_loss: 2.9290 - val_accuracy: 0.1783
Epoch 8/20
19/19 [

In [9]:
model.save('birds.h5')

In [10]:
import numpy as np
from tensorflow.keras.preprocessing import image

In [11]:
output = ['rebimg','wcrsrt','jglowl','ibicrw','mgprob','hsparo',
         'indvul','himgri','himbul','gretit','hilpig','cbrtsh',
         'cmnmyn','bonegl','brhkyt','blasti']
print(output)

['rebimg', 'wcrsrt', 'jglowl', 'ibicrw', 'mgprob', 'hsparo', 'indvul', 'himgri', 'himbul', 'gretit', 'hilpig', 'cbrtsh', 'cmnmyn', 'bonegl', 'brhkyt', 'blasti']


In [12]:
img1 = image.load_img("/content/test_data/test_data/jglowl/_D32_10584.jpg",target_size=(120,120))
img1 = image.img_to_array(img1)
img1 = np.expand_dims(img1,axis=0)
pred = np.argmax(model.predict(img1))
print(pred)
print(output[pred])

1/1 [==============================] - 0s 163ms/step
15
blasti


# Model Tuning(with Drop out , batch normalisation , early stopping)


In [13]:
from tensorflow.keras.layers import BatchNormalization,Dropout

In [14]:
model = Sequential([
    Convolution2D(12,(3,3),activation = 'relu',input_shape=(120,120,3)),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Dropout(0.2),
    Convolution2D(24,(3,3),activation = 'relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Dropout(0.2),
    Convolution2D(36,(3,3),activation = 'relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Dropout(0.2),
    Flatten(),
    Dense(62,activation = 'relu'),
    BatchNormalization(),
    Dropout(0.1),
    Dense(32,activation = 'relu'),
    Dense(16,activation = 'relu'),
    Dense(16,activation = 'softmax')
])

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 118, 118, 12)      336       
                                                                 
 batch_normalization (BatchN  (None, 118, 118, 12)     48        
 ormalization)                                                   
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 59, 59, 12)       0         
 2D)                                                             
                                                                 
 dropout (Dropout)           (None, 59, 59, 12)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 57, 57, 24)        2616      
                                                                 
 batch_normalization_1 (Batc  (None, 57, 57, 24)      

In [16]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='categorical_crossentropy')

In [17]:
# Early stopping
from tensorflow.keras.callbacks import EarlyStopping

In [18]:
early_stop = EarlyStopping(monitor = 'val_accuracy',patience = 8)

In [19]:
model_fit = model.fit(train,epochs =30,
                     validation_data = test ,
                      batch_size=5,
                      callbacks=early_stop)

Epoch 1/30
19/19 [==============================] - 93s 5s/step - loss: 2.8809 - accuracy: 0.1067 - val_loss: 2.7920 - val_accuracy: 0.0955
Epoch 2/30
19/19 [==============================] - 85s 5s/step - loss: 2.4582 - accuracy: 0.2467 - val_loss: 2.9162 - val_accuracy: 0.0573
Epoch 3/30
19/19 [==============================] - 84s 5s/step - loss: 2.3542 - accuracy: 0.2600 - val_loss: 3.2419 - val_accuracy: 0.0573
Epoch 4/30
19/19 [==============================] - 86s 5s/step - loss: 2.2921 - accuracy: 0.3067 - val_loss: 3.3989 - val_accuracy: 0.0573
Epoch 5/30
19/19 [==============================] - 87s 5s/step - loss: 2.2022 - accuracy: 0.2867 - val_loss: 4.0729 - val_accuracy: 0.0573
Epoch 6/30
19/19 [==============================] - 85s 5s/step - loss: 2.1241 - accuracy: 0.3667 - val_loss: 3.8623 - val_accuracy: 0.0573
Epoch 7/30
19/19 [==============================] - 84s 5s/step - loss: 2.0117 - accuracy: 0.3867 - val_loss: 4.3069 - val_accuracy: 0.0573
Epoch 8/30
19/19 [==

In [27]:
img1 = image.load_img("/content/test_data/test_data/jglowl/_D32_10584.jpg",target_size=(120,120))
img1 = image.img_to_array(img1)
img1 = np.expand_dims(img1,axis=0)
print(img1)
pred = np.argmax(model.predict(img1))
print(pred)
print(output[pred])

[[[[ 54.  55.  57.]
   [ 66.  71.  74.]
   [118. 116. 129.]
   ...
   [ 50.  43.  37.]
   [ 68.  63.  57.]
   [ 83.  81.  58.]]

  [[ 56.  59.  64.]
   [ 72.  73.  78.]
   [112. 114. 113.]
   ...
   [ 33.  32.  30.]
   [ 59.  65.  53.]
   [ 54.  62.  51.]]

  [[ 64.  64.  64.]
   [ 97. 102. 106.]
   [123. 115. 113.]
   ...
   [ 47.  49.  46.]
   [ 69.  70.  64.]
   [ 52.  60.  62.]]

  ...

  [[112. 108. 105.]
   [103.  98.  95.]
   [ 79.  80.  85.]
   ...
   [ 42.  46.  47.]
   [ 38.  42.  51.]
   [132. 132. 140.]]

  [[108. 108. 108.]
   [ 96.  98.  97.]
   [ 90.  90.  88.]
   ...
   [ 30.  35.  39.]
   [ 40.  44.  45.]
   [ 36.  34.  35.]]

  [[ 95.  96.  90.]
   [114. 111. 102.]
   [123. 115. 112.]
   ...
   [ 41.  47.  47.]
   [ 68.  72.  81.]
   [ 51.  55.  56.]]]]
1/1 [==============================] - 0s 27ms/step
15
blasti
